### ISSUE TITLE
Not Working with Rails 5.1.6

### ISSUE THREAD

**Issue by saleheenkhan** [webgradus/kms_feedback#1]
Hi,

I am Trying to install this extension on KMS Cms. I am Getting Below Error

![capture](https://user-images.githubusercontent.com/8937927/38894585-72f6c41e-42af-11e8-83a5-4bddd18aac34.JPG)

My Rails Version 5.1.6 & Ruby Version ruby 2.4.3p205

Can you please help me on this?

Thanks in Advance

**Comment by GarPit** [comment]
Hello @saleheenkhan 

Thanks for reporting this, this extension is a little bit outdated. And even its functionality may be replaced with `kms_models` which has form submission for Models. Just need to make email notifications.

I think I'll update its dependency soon and then start to implementing substitution of its functionality in APIQ Models

**Comment by saleheenkhan** [comment]
Thank you for the Update
